### PR TITLE
Upgrade to Ecto 3, Elixir 1.8 + latest Phoenix 1.3

### PR DESCRIPTION
**Pull request by ysbaddaden**
**The road to Ecto 3**:

- [x] remove direct dependency on Timex.Ecto;
- [x] remove usages of deprecated Timex.Ecto.DateTime —replaced with `:utc_datetime`;
- [x] remove usages of deprecated Ecto.DateTime —replaced with `:utc_datetime` for fields (only found in SurveyLogEntry) and DateTime for methods;
- [x] start using DateTime over Timex.DateTime when possible;
- [x] upgrade Ecto from v2.1 to v2.2;
- [x] upgrade Coherence:
  - [ ] :warning: may impact `alto_guisso` (nope),
  - [ ] :warning: may need to also upgrade Elixir (yes -> 1.7) and Phoenix (nope);
  - [x] **alternative**: fix upgrade warnings in Coherence 3.2;
- [x] upgrade phoenix_ecto:
  - [ ] :warning: ~~may require to upgrade to Phoenix 1.4~~ (not needed);
- [x] upgrade ex_machina (>= 2.2.2);
- [x] upgrade to Ecto 3;
- [x] migrate from [mariaex](https://hex.pm/package/mariaex) to [myxql](https://hex.pm/package/myxql) driver (breaks CI & mariaex support was removed in Ecto 3.2)

**Bumps on the road**:
- [x] upgrade to Elixir 1.6 —mostly for the `DateTime.truncate/2` method;
- [x] upgrade to Elixir 1.7 —required by dependencies;
  - [x] upgrade to Sentry 7.x to take advantage of Logger of OTP 21+ (instead of the deprecated `:error_logger`);
- [x] upgrade to Elixir 1.8 —required by Ecto 3.5;
- [x] upgrade to Phoenix 1.3.4 —fixes a compilation warning after upgrading to Elixir 1.6.

**Bugs**:
- [x] The Floip tests exhibit an issue where DateTime's microseconds are being rounded instead of truncated ([MySQL issue](https://bugs.mysql.com/bug.php?id=76948)), which results in the date comparison failing in tests because of a one-second difference —for example: we expect 00:00:09 but we get 00:00:10 instead.

  ~~This should be fixed after upgrading to Ecto 3, since `:utc_datetime` will have seconds precision instead of microseconds~~ That seems to be fixed :crossed_fingers:

### CODE REVIEW

**Comment by ysbaddaden** [comment]
I'm failing to upgrade Ecto from v2.1 to v2.2 because of a compilation deadlock, caused by some circular dependencies (or something). This is exactly this issue: https://github.com/elixir-ecto/ecto/issues/2519. The problem is that I only see `X belongs_to Y` and `Y has_many X` for the time being, and they're supposed to be working. We probably do something that we shouldn't somewhere, but, for the time being I'm lost :sob: 

ping @ggiraldez @anaPerezGhiglia 

For example:
```
== Compilation error in file web/models/floip_endpoint.ex ==
** (CompileError)  deadlocked waiting on module Ask.Survey
    (elixir) lib/code.ex:892: Code.ensure_compiled/1
    (elixir) lib/code.ex:912: Code.ensure_compiled?/1
    lib/ecto/association.ex:718: Ecto.Association.BelongsTo.after_compile_validation/1
    lib/ecto/schema.ex:1655: anonymous fn/4 in Ecto.Schema.__after_compile__/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/ecto/schema.ex:1653: Ecto.Schema.__after_compile__/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

Compilation failed because of a deadlock between files.
The following files depended on the following modules:

                        web/models/response.ex => Ask.Respondent
                web/models/respondent_group.ex => Ask.Survey
      web/controllers/respondent_controller.ex => Ask.Survey
           web/models/completed_respondents.ex => Ask.Survey
                    web/models/activity_log.ex => Ask.Survey
                    web/models/panel_survey.ex => Ask.Project
  web/models/respondent_disposition_history.ex => Ask.Respondent
            web/models/survey_questionnaire.ex => Ask.Survey
                          web/models/folder.ex => Ask.Survey
                    web/models/quota_bucket.ex => Ask.Survey
    lib/ask/runtime/questionnaire_simulator.ex => Ask.Survey
                  lib/ask/retries_histogram.ex => Ask.Survey
                     lib/ask/runtime/broker.ex => Ask.Survey
                          web/models/survey.ex => Ask.RespondentStats
          web/controllers/survey_controller.ex => Ask.Survey
                      web/views/survey_view.ex => Ask.Survey
                web/models/survey_log_entry.ex => Ask.Survey
                      web/models/retry_stat.ex => Ask.Respondent
                         web/models/project.ex => Ask.Survey
                 web/models/project_channel.ex => Ask.Project
                      web/models/respondent.ex => Ask.Survey
                web/models/respondent_stats.ex => Ask.Survey
                  web/models/floip_endpoint.ex => Ask.Survey
```

**Comment by ggiraldez** [comment]
> I think the culprit is `Ask.Survey`, everything points to it. I have to find what, where, is trying to load it, and creates the compile-time circular dependency deadlock.

The problem seems to be in [this require](https://github.com/instedd/surveda/blob/fix/upgrade-to-ecto-3/web/models/survey.ex#L5) which is necessary to use the `respondant_count` macro. This was introduced in a22198fc3e36bfb14f222054998411f5397cecc8. I'm not sure how to fix it, though I suspect you'll need to remove/replace those macro calls, and maybe undo some of the changes in that commit.

**Comment by ysbaddaden** [comment]
Thank you @ggiraldez :bow:

The `require Ask.RespondentStats` and the `respondent_count` macro calls do cause the recursion issue. I'm trying to move the `respondents_by_disposition` and `respondents_by_state` methods that depend on the macro from `Ask.Survey` to `Ask.RespondentStats`, that should do it.

**Comment by ysbaddaden** [comment]
Yeah, specs are :heavy_check_mark: with Ecto 3.0.0 :green_apple: ! CI is failing because we treat warnings as errors, and the `Ecto.Adapters.MySQL` (uses [mariaex](hex.pm/packages/mariaex) last updated 3 years ago) is deprecated in favor to `Ecto.Adapters.MyXQL` (uses [myxql](https://github.com/elixir-ecto/myxql) last updated 1 week ago).

A quick try of the UI seemed to work, and I could run a few simulators. I'll test more thoroughly, by creating a project, a questionnaire/folder/panel survey and running a wave :)

**Comment by ysbaddaden** [comment]
Sigh, CI is broken because of migrations :sob:

**Comment by ysbaddaden** [comment]
I worked around the migration issue by dumping the SQL structure and adding it to the repository. Running tests on CI now merely loads the current SQL structure.

The structure will be dumped automatically whenever running migrations in the dev environment (not within tests).

**Comment by ysbaddaden** [comment]
I just notice that we should upgrade Sentry to 7.x for better support of Elixir 1.7 and OTP 21+ that changed a bunch of things around exceptions.

**Pull request merged**
