### PR TITLE
Replace occurrence with wave

### PR DESCRIPTION
**Pull request by ftarulla**
Related #1972 

Replaced with `wave`:
- occurrence
- ocurrence
- occurence
- ocurence

### CODE REVIEW

**Comment by ysbaddaden** [comment]
AFAIK there is still `occurrence` :)

**Comment by ftarulla** [comment]
> AFAIK there is still `occurrence` :)

yeah! I was still working on the rename. I leave the actual `occurrence` until last 😆

**Review by ysbaddaden — APPROVED** [review]
Ready to merge right after #1977!

**Comment by ysbaddaden** [comment]
Merged in the `develop` branch.

**Pull request merged**
